In [1]:
import pandas as pd
from pathlib import Path

# EPC folder
base_cened = Path(r"F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED")

file1 = base_cened / "bbky-sde5_version_17245.xlsx"
file2 = base_cened / "Database_CENED+2_-_Certificazione_Energetica_degli_Edifici_20251128.xlsx"

file1, file2

(WindowsPath('F:/Building Engineering - Polytechnic University of Turin/Masters Thesis/23-11-2025/Data Collections/CENED/bbky-sde5_version_17245.xlsx'),
 WindowsPath('F:/Building Engineering - Polytechnic University of Turin/Masters Thesis/23-11-2025/Data Collections/CENED/Database_CENED+2_-_Certificazione_Energetica_degli_Edifici_20251128.xlsx'))

In [2]:
def quick_excel_inspect(path, nrows=5):
    print("\n" + "="*80)
    print(f"FILE: {path}")
    print("="*80)

    try:
        xls = pd.ExcelFile(path)
    except Exception as e:
        print("Error opening file:", e)
        return
    
    print("Available sheets:")
    for sheet in xls.sheet_names:
        print(f"  - {sheet}")

    for sheet in xls.sheet_names:
        print("\n" + "-"*40)
        print(f"SHEET: {sheet}")
        print("-"*40)

        try:
            df = pd.read_excel(xls, sheet_name=sheet, nrows=nrows)
            print(f"Preview shape: {df.shape}")
            print("Columns:", list(df.columns))
            print(df.head())
        except Exception as e:
            print("Error reading sheet:", e)

In [3]:
quick_excel_inspect(file1, nrows=5)
quick_excel_inspect(file2, nrows=5)

================================================================================
FILE: F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\bbky-sde5_version_17245.xlsx
================================================================================
Error opening file: [Errno 2] No such file or directory: 'F:\\Building Engineering - Polytechnic University of Turin\\Masters Thesis\\23-11-2025\\Data Collections\\CENED\\bbky-sde5_version_17245.xlsx'

================================================================================
FILE: F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\Database_CENED+2_-_Certificazione_Energetica_degli_Edifici_20251128.xlsx
================================================================================
Error opening file: [Errno 2] No such file or directory: 'F:\\Building Engineering - Polytechnic University of Turin\\Masters Thesis\\23-11-2025\\Data Collections\\CENED\\Database_CENED+2_-_Certificazione_Energetica_degli_Edifici_20251128.xlsx'

In [4]:
from pathlib import Path

base_cened = Path(r"F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED")

print("CENED folder exists:", base_cened.exists())
print("\nFiles inside CENED folder:")
for p in base_cened.iterdir():
    print("  ->", repr(p.name))

CENED folder exists: True

Files inside CENED folder:
  -> 'bbky-sde5_version_17245.csv'
  -> 'Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv'

In [5]:
# Find all Excel-like files in the folder
excel_files = sorted(base_cened.glob("*.xls*"))

print("Detected Excel files:")
for i, f in enumerate(excel_files, start=1):
    print(f"{i}: {f.name}")

excel_files

Detected Excel files:

[]

In [6]:
# Inspect each detected Excel file using the helper function

for path in excel_files:
    quick_excel_inspect(path, nrows=5)

In [7]:
from pathlib import Path

base_cened = Path(r"F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED")

print("CENED folder exists:", base_cened.exists())
print("\nFiles inside CENED folder:")
for p in base_cened.iterdir():
    print("  ->", repr(p.name))

# Find all CSV files
csv_files = sorted(base_cened.glob("*.csv"))

print("\nDetected CSV files:")
for i, f in enumerate(csv_files, start=1):
    print(f"{i}: {f.name}")

csv_files

CENED folder exists: True

Files inside CENED folder:
  -> 'bbky-sde5_version_17245.csv'
  -> 'Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv'

Detected CSV files:
1: bbky-sde5_version_17245.csv
2: Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv

[WindowsPath('F:/Building Engineering - Polytechnic University of Turin/Masters Thesis/23-11-2025/Data Collections/CENED/bbky-sde5_version_17245.csv'),
 WindowsPath('F:/Building Engineering - Polytechnic University of Turin/Masters Thesis/23-11-2025/Data Collections/CENED/Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv')]

In [8]:
import pandas as pd
import csv

def detect_delimiter(path, sample_size=50000):
    """Detect the delimiter of a CSV file using csv.Sniffer."""
    with open(path, "r", encoding="latin1") as f:  # latin1 is tolerant for weird chars
        sample = f.read(sample_size)
    sniffer = csv.Sniffer()
    dialect = sniffer.sniff(sample, delimiters=[",", ";", "\t", "|"])
    return dialect.delimiter

def quick_csv_inspect(path, nrows=5):
    print("\n" + "="*80)
    print(f"FILE: {path}")
    print("="*80)

    try:
        delim = detect_delimiter(path)
        print(f"Detected delimiter: {repr(delim)}")
    except Exception as e:
        print("Could not detect delimiter, defaulting to comma. Error:", e)
        delim = ","

    try:
        df = pd.read_csv(path, sep=delim, nrows=nrows, low_memory=False)
    except Exception as e:
        print("Error reading CSV:", e)
        return

    print(f"Preview shape (first {nrows} rows): {df.shape}")
    print("Columns:")
    print(list(df.columns))
    print("\nHead:")
    print(df.head())

In [9]:
for path in csv_files:
    quick_csv_inspect(path, nrows=5)

================================================================================
FILE: F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\bbky-sde5_version_17245.csv
================================================================================
Detected delimiter: ','
Preview shape (first 5 rows): (5, 210)
Columns:
['ci_anno_installazione_2', 'tpc_anno_installazione_2', 'tpc_anno_installazione_1', 'ill_anno_installazione', 'pfr_anno_installazione_2', 'pfr_anno_installazione_1', 'ic_anno_installazione', 'pa_anno_installazione', 'ci_anno_installazione_1', 'ce_anno_installazione_2', 'ce_anno_installazione_1', 'sez_censimento', 'cod_ape', 'data_ins', 'residenziale', 'non_residenziale', 'comune_catastale', 'sezione', 'foglio', 'particella', 'subalterno', 'proprieta_pubblica', 'uso_pubblico', 'classificazione_dpr', 'intero_edificio', 'unita_immobiliare', 'gruppo_unita_immobiliari', 'numero_unita_immobiliari', 'nuova_costruzione', 'passaggio_proprieta', 'locazione', 'ristrutturazione_importante', 'riqualificazione_energetica', 'oggetto_altro', 'oggetto_altro_txt', 'regione', 'comune', 'indirizzo', 'piano', 'interno', 'wgs84_x', 'wgs84_y', 'location', 'location_state', 'location_address', 'location_zip', 'location_city', 'zona_climatica', 'anno_costruzione', 'superf_utile_riscaldata', 'superf_utile_raffrescata', 'volume_lordo_riscaldato', 'volume_lordo_raffrescato', 'climatizzazione_invernale', 'climatizzazione_estiva', 'ventilazione_meccanica', 'prod_acqua_calda_sanitaria', 'illuminazione', 'trasporto_persone_cose', 'emoticon_inverno', 'emoticon_estate', 'edificio_energia_quasi_zero', 'classe_energetica', 'ep_gl_nren', 'y', 'z', 'ep_gl_ren', 'emissioni_co2', 'consumi_energia_elettrica', 'consumi_gas_naturale', 'consumi_gpl', 'consumi_carbone', 'consumi_gasolio', 'consumi_biomasse_solide', 'consumi_biomasse_liquide', 'consumi_biomasse_gassose', 'consumi_solare_fotovoltaico', 'consumi_solare_termico', 'consumi_eolico', 'consumi_teleriscaldamento', 'consumi_teleraffrescamento', 'consumi_altro', 'riq_classe_ragg', 'riq_ep_gl_nren_ragg', 'ds_codice_intervento_1', 'ds_tipo_intervento_1', 'fl_comporta_ristrut_1', 'nm_tempo_ritorno_investim_1', 'ds_classe_raggiungibile_1', 'nm_ep_gl_nren_raggiung_1', 'ds_codice_intervento_2', 'ds_tipo_intervento_2', 'fl_comporta_ristrut_2', 'nm_tempo_ritorno_investim_2', 'ds_classe_raggiungibile_2', 'nm_ep_gl_nren_raggiung_2', 'ds_codice_intervento_3', 'ds_tipo_intervento_3', 'fl_comporta_ristrut_3', 'nm_tempo_ritorno_investim_3', 'ds_classe_raggiungibile_3', 'nm_ep_gl_nren_raggiung_3', 'ds_codice_intervento_4', 'ds_tipo_intervento_4', 'fl_comporta_ristrut_4', 'nm_tempo_ritorno_investim_4', 'ds_classe_raggiungibile_4', 'nm_ep_gl_nren_raggiung_4', 'ds_codice_intervento_5', 'ds_tipo_intervento_5', 'fl_comporta_ristrut_5', 'nm_tempo_ritorno_investim_5', 'ds_classe_raggiungibile_5', 'nm_ep_gl_nren_raggiung_5', 'ds_codice_intervento_6', 'ds_tipo_intervento_6', 'fl_comporta_ristrut_6', 'nm_tempo_ritorno_investim_6', 'ds_classe_raggiungibile_6', 'nm_ep_gl_nren_raggiung_6', 'ds_codice_intervento_7', 'ds_tipo_intervento_7', 'fl_comporta_ristrut_7', 'nm_tempo_ritorno_investim_7', 'ds_classe_raggiungibile_7', 'nm_ep_gl_nren_raggiung_7', 'energia_esportata', 'vettore_energetico', 'superficie_disperdente', 'rapporto_sv', 'ep_h_nd', 'a_sol_est_a_sup_utile', 'y_ie', 'ci_tipo_impianto_1', 'ci_codice_catasto_1', 'ci_vettore_energetico_1', 'ci_potenza_nominale_1', 'ci_tipo_impianto_2', 'ci_vettore_energetico_2', 'ci_potenza_nominale_2', 'ci_efficienza_media', 'ci_epren', 'ci_epnren', 'ce_tipo_impianto_1', 'ce_vettore_energetico_1', 'ce_potenza_nominale_1', 'ce_tipo_impianto_2', 'ce_vettore_energetico_2', 'ce_potenza_nominale_2', 'ce_efficienza_media', 'ce_epren', 'ce_epnren', 'pa_tipo_impianto', 'pa_vettore_energetico', 'pa_potenza_nominale', 'pa_efficienza_media', 'pa_epren', 'pa_epnren', 'ic_tipo_impianto', 'ic_vettore_energetico', 'ic_potenza_nominale', 'ic_efficienza_media', 'ic_epren', 'ic_epnren', 'pfr_tipo_impianto_1', 'pfr_vettore_energetico_1', 'pfr_potenza_nominale_1', 'pfr_efficienza_media_1', 'pfr_epren_1', 'pfr_epnren_1', 'pfr_tipo_impianto_2', 'pfr_vettore_energetico_2', 'pfr_potenza_nominale_2', 'pfr_efficienza_media_2', 'pfr_epren_2', 'pfr_epnren_2', 'vm_tipo_impianto', 'vm_anno_installazione', 'vm_vettore_energetico', 'vm_potenza_nominale', 'vm_efficienza_media', 'vm_epren', 'vm_epnren', 'ill_tipo_impianto', 'ill_vettore_energetico', 'ill_potenza_nominale', 'ill_efficienza_media', 'ill_epren', 'ill_epnren', 'tpc_tipo_impianto_1', 'tpc_vettore_energetico_1', 'tpc_potenza_nominale_1', 'tpc_efficienza_media_1', 'tpc_epren_1', 'tpc_epnren_1', 'tpc_tipo_impianto_2', 'tpc_vettore_energetico_2', 'tpc_potenza_nominale_2', 'tpc_efficienza_media_2', 'tpc_epren_2', 'tpc_epnren_2', 'sopralluogo', 'sw_requisiti', 'sw_semplificato', 'ente_pubblico', 'tecnico_abilitato', 'societa', 'nome_denominazione_cert', 'titolo_cert', 'ordine_cert']

Head:
   ci_anno_installazione_2  tpc_anno_installazione_2  \
0                      NaN                       NaN
1                      NaN                       NaN
2                      NaN                       NaN
3                      NaN                       NaN
4                      NaN                       NaN

   tpc_anno_installazione_1  ill_anno_installazione  pfr_anno_installazione_2  \
0                       NaN                     NaN                       NaN
1                       NaN                     NaN                       NaN
2                       NaN                     NaN                       NaN
3                       NaN                     NaN                       NaN
4                       NaN                     NaN                       NaN

   pfr_anno_installazione_1  ic_anno_installazione  pa_anno_installazione  \
0                       NaN                    NaN                    NaN
1                       NaN                    NaN                 2009.0
2                       NaN                    NaN                 1998.0
3                       NaN                    NaN                 2006.0
4                       NaN                    NaN                    NaN

   ci_anno_installazione_1  ce_anno_installazione_2  ...  tpc_epnren_2  \
0                      NaN                      NaN  ...           NaN
1                   2009.0                      NaN  ...           NaN
2                   1998.0                      NaN  ...           NaN
3                   2006.0                      NaN  ...           NaN
4                      NaN                      NaN  ...           NaN

   sopralluogo  sw_requisiti sw_semplificato  ente_pubblico  \
0         True          True           False          False
1         True          True           False          False
2         True          True           False          False
3         True          True           False          False
4         True          True           False          False

   tecnico_abilitato societa nome_denominazione_cert  \
0               True   False          MONIA CANZIANI
1               True   False     Carmine Di Costanzo
2               True   False           elio casanovi
3               True   False           debora perina
4               True   False         Gabriele Dogini

                         titolo_cert              ordine_cert
0    Laurea magistrale in ingegneria   Ordine degli ingegneri
1                Diploma di geometra    Collegio dei geometri
2    Laurea magistrale in ingegneria   Ordine degli ingegneri
3  Diploma di laurea in architettura  Ordine degli architetti
4                Diploma di geometra    Collegio dei geometri

[5 rows x 210 columns]

================================================================================
FILE: F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv
================================================================================
Detected delimiter: ','
Preview shape (first 5 rows): (5, 198)
Columns:
['COD_APE', 'DATA_INS', 'RESIDENZIALE', 'NON_RESIDENZIALE', 'COMUNE_CATASTALE', 'PROPRIETA_PUBBLICA', 'USO_PUBBLICO', 'CLASSIFICAZIONE_DPR', 'INTERO_EDIFICIO', 'UNITA_IMMOBILIARE', 'GRUPPO_UNITA_IMMOBILIARI', 'NUMERO_UNITA_IMMOBILIARI', 'NUOVA_COSTRUZIONE', 'PASSAGGIO_PROPRIETA', 'LOCAZIONE', 'RISTRUTTURAZIONE_IMPORTANTE', 'RIQUALIFICAZIONE_ENERGETICA', 'OGGETTO_ALTRO', 'OGGETTO_ALTRO_TXT', 'REGIONE', 'COMUNE', 'INDIRIZZO', 'PIANO', 'INTERNO', 'ZONA_CLIMATICA', 'ANNO_COSTRUZIONE', 'SUPERF_UTILE_RISCALDATA', 'SUPERF_UTILE_RAFFRESCATA', 'VOLUME_LORDO_RISCALDATO', 'VOLUME_LORDO_RAFFRESCATO', 'CLIMATIZZAZIONE_INVERNALE', 'CLIMATIZZAZIONE_ESTIVA', 'VENTILAZIONE_MECCANICA', 'PROD_ACQUA_CALDA_SANITARIA', 'ILLUMINAZIONE', 'TRASPORTO_PERSONE_COSE', 'PI', 'PE', 'EDIFICIO_ENERGIA_QUASI_ZERO', 'CLASSE_ENERGETICA', 'EP_GL_NREN', 'Y', 'Z', 'EP_GL_REN', 'EMISSIONI_CO2', 'CONSUMI_ENERGIA_ELETTRICA', 'CONSUMI_GAS_NATURALE', 'CONSUMI_GPL', 'CONSUMI_CARBONE', 'CONSUMI_GASOLIO', 'CONSUMI_BIOMASSE_SOLIDE', 'CONSUMI_BIOMASSE_LIQUIDE', 'CONSUMI_BIOMASSE_GASSOSE', 'CONSUMI_SOLARE_FOTOVOLTAICO', 'CONSUMI_SOLARE_TERMICO', 'CONSUMI_EOLICO', 'CONSUMI_TELERISCALDAMENTO', 'CONSUMI_TELERAFFRESCAMENTO', 'CONSUMI_ALTRO', 'RIQ_CLASSE_RAGG', 'RIQ_EP_GL_NREN_RAGG', 'DS_CODICE_INTERVENTO_1', 'DS_TIPO_INTERVENTO_1', 'FL_COMPORTA_RISTRUT_1', 'NM_TEMPO_RITORNO_INVESTIM_1', 'DS_CLASSE_RAGGIUNGIBILE_1', 'NM_EP_GL_NREN_RAGGIUNG_1', 'DS_CODICE_INTERVENTO_2', 'DS_TIPO_INTERVENTO_2', 'FL_COMPORTA_RISTRUT_2', 'NM_TEMPO_RITORNO_INVESTIM_2', 'DS_CLASSE_RAGGIUNGIBILE_2', 'NM_EP_GL_NREN_RAGGIUNG_2', 'DS_CODICE_INTERVENTO_3', 'DS_TIPO_INTERVENTO_3', 'FL_COMPORTA_RISTRUT_3', 'NM_TEMPO_RITORNO_INVESTIM_3', 'DS_CLASSE_RAGGIUNGIBILE_3', 'NM_EP_GL_NREN_RAGGIUNG_3', 'DS_CODICE_INTERVENTO_4', 'DS_TIPO_INTERVENTO_4', 'FL_COMPORTA_RISTRUT_4', 'NM_TEMPO_RITORNO_INVESTIM_4', 'DS_CLASSE_RAGGIUNGIBILE_4', 'NM_EP_GL_NREN_RAGGIUNG_4', 'DS_CODICE_INTERVENTO_5', 'DS_TIPO_INTERVENTO_5', 'FL_COMPORTA_RISTRUT_5', 'NM_TEMPO_RITORNO_INVESTIM_5', 'DS_CLASSE_RAGGIUNGIBILE_5', 'NM_EP_GL_NREN_RAGGIUNG_5', 'DS_CODICE_INTERVENTO_6', 'DS_TIPO_INTERVENTO_6', 'FL_COMPORTA_RISTRUT_6', 'NM_TEMPO_RITORNO_INVESTIM_6', 'DS_CLASSE_RAGGIUNGIBILE_6', 'NM_EP_GL_NREN_RAGGIUNG_6', 'DS_CODICE_INTERVENTO_7', 'DS_TIPO_INTERVENTO_7', 'FL_COMPORTA_RISTRUT_7', 'NM_TEMPO_RITORNO_INVESTIM_7', 'DS_CLASSE_RAGGIUNGIBILE_7', 'NM_EP_GL_NREN_RAGGIUNG_7', 'ENERGIA_ESPORTATA', 'VETTORE_ENERGETICO', 'SUPERFICIE_DISPERDENTE', 'RAPPORTO_SV', 'EP_H_ND', 'A_SOL_EST_A_SUP_UTILE', 'Y_IE', 'CI_TIPO_IMPIANTO_1', 'CI_ANNO_INSTALLAZIONE_1', 'CI_CODICE_CATASTO_1', 'CI_VETTORE_ENERGETICO_1', 'CI_POTENZA_NOMINALE_1', 'CI_TIPO_IMPIANTO_2', 'CI_ANNO_INSTALLAZIONE_2', 'CI_VETTORE_ENERGETICO_2', 'CI_POTENZA_NOMINALE_2', 'CI_EFFICIENZA_MEDIA', 'CI_EPREN', 'CI_EPNREN', 'CE_TIPO_IMPIANTO_1', 'CE_ANNO_INSTALLAZIONE_1', 'CE_VETTORE_ENERGETICO_1', 'CE_POTENZA_NOMINALE_1', 'CE_TIPO_IMPIANTO_2', 'CE_ANNO_INSTALLAZIONE_2', 'CE_VETTORE_ENERGETICO_2', 'CE_POTENZA_NOMINALE_2', 'CE_EFFICIENZA_MEDIA', 'CE_EPREN', 'CE_EPNREN', 'PA_TIPO_IMPIANTO', 'PA_ANNO_INSTALLAZIONE', 'PA_VETTORE_ENERGETICO', 'PA_POTENZA_NOMINALE', 'PA_EFFICIENZA_MEDIA', 'PA_EPREN', 'PA_EPNREN', 'IC_TIPO_IMPIANTO', 'IC_ANNO_INSTALLAZIONE', 'IC_VETTORE_ENERGETICO', 'IC_POTENZA_NOMINALE', 'IC_EFFICIENZA_MEDIA', 'IC_EPREN', 'IC_EPNREN', 'PFR_TIPO_IMPIANTO_1', 'PFR_ANNO_INSTALLAZIONE_1', 'PFR_VETTORE_ENERGETICO_1', 'PFR_POTENZA_NOMINALE_1', 'PFR_EFFICIENZA_MEDIA_1', 'PFR_EPREN_1', 'PFR_EPNREN_1', 'PFR_TIPO_IMPIANTO_2', 'PFR_ANNO_INSTALLAZIONE_2', 'PFR_VETTORE_ENERGETICO_2', 'PFR_POTENZA_NOMINALE_2', 'PFR_EFFICIENZA_MEDIA_2', 'PFR_EPREN_2', 'PFR_EPNREN_2', 'VM_TIPO_IMPIANTO', 'VM_ANNO_INSTALLAZIONE', 'VM_VETTORE_ENERGETICO', 'VM_POTENZA_NOMINALE', 'VM_EFFICIENZA_MEDIA', 'VM_EPREN', 'VM_EPNREN', 'ILL_TIPO_IMPIANTO', 'ILL_ANNO_INSTALLAZIONE', 'ILL_VETTORE_ENERGETICO', 'ILL_POTENZA_NOMINALE', 'ILL_EFFICIENZA_MEDIA', 'ILL_EPREN', 'ILL_EPNREN', 'TPC_TIPO_IMPIANTO_1', 'TPC_ANNO_INSTALLAZIONE_1', 'TPC_VETTORE_ENERGETICO_1', 'TPC_POTENZA_NOMINALE_1', 'TPC_EFFICIENZA_MEDIA_1', 'TPC_EPREN_1', 'TPC_EPNREN_1', 'TPC_TIPO_IMPIANTO_2', 'TPC_ANNO_INSTALLAZIONE_2', 'TPC_VETTORE_ENERGETICO_2', 'TPC_POTENZA_NOMINALE_2', 'TPC_EFFICIENZA_MEDIA_2', 'TPC_EPREN_2', 'TPC_EPNREN_2', 'SOPRALLUOGO', 'SW_REQUISITI', 'SW_SEMPLIFICATO', 'ENTE_PUBBLICO', 'TECNICO_ABILITATO', 'SOCIETA', 'TITOLO_CERT', 'ORDINE_CERT', 'SEZ_CENSIMENTO']

Head:
         COD_APE    DATA_INS  RESIDENZIALE  NON_RESIDENZIALE COMUNE_CATASTALE  \
0  1514602104118  13/09/2018          True             False           MILANO
1  1514600314321  28/01/2021          True             False           MILANO
2  1514602122717  24/07/2017          True             False           MILANO
3  1514601459317  24/05/2017          True             False           MILANO
4  1514603613816  19/12/2016          True             False           MILANO

   PROPRIETA_PUBBLICA  USO_PUBBLICO CLASSIFICAZIONE_DPR  INTERO_EDIFICIO  \
0               False         False              E.1(1)            False
1               False         False              E.1(1)            False
2               False         False              E.1(1)            False
3               False         False              E.1(1)            False
4               False         False              E.1(1)            False

   UNITA_IMMOBILIARE  ...  TPC_EPNREN_2  SOPRALLUOGO  SW_REQUISITI  \
0               True  ...             0         True          True
1               True  ...             0         True          True
2               True  ...             0         True          True
3               True  ...             0         True          True
4               True  ...             0         True          True

   SW_SEMPLIFICATO  ENTE_PUBBLICO  TECNICO_ABILITATO  SOCIETA  \
0            False          False               True    False
1            False          False               True    False
2            False          False               True    False
3            False          False               True    False
4            False          False               True    False

                                         TITOLO_CERT  \
0                    Diploma di laurea in ingegneria
1                  Diploma di laurea in architettura
2                                Diploma di geometra
3  Diploma di perito industriale o di istruzione ...
4                  Diploma di laurea in architettura

                       ORDINE_CERT SEZ_CENSIMENTO
0           Ordine degli ingegneri            NaN
1          Ordine degli architetti            NaN
2            Collegio dei geometri            NaN
3  Collegio dei periti industriali            NaN
4          Ordine degli architetti            NaN

[5 rows x 198 columns]

In [10]:
# ============================================
# 10.7.4 – Choose main EPC dataset (CENED+2)
# ============================================

epc_path = base_cened / "Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv"
print(epc_path, epc_path.exists())

# Load a small sample with proper parsing
epc_sample = pd.read_csv(
    epc_path,
    sep=",",
    nrows=1000,          # just a sample for exploration
    low_memory=False
)

epc_sample.shape, epc_sample.columns[:20]

F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv True

((1000, 198),
 Index(['COD_APE', 'DATA_INS', 'RESIDENZIALE', 'NON_RESIDENZIALE',
        'COMUNE_CATASTALE', 'PROPRIETA_PUBBLICA', 'USO_PUBBLICO',
        'CLASSIFICAZIONE_DPR', 'INTERO_EDIFICIO', 'UNITA_IMMOBILIARE',
        'GRUPPO_UNITA_IMMOBILIARI', 'NUMERO_UNITA_IMMOBILIARI',
        'NUOVA_COSTRUZIONE', 'PASSAGGIO_PROPRIETA', 'LOCAZIONE',
        'RISTRUTTURAZIONE_IMPORTANTE', 'RIQUALIFICAZIONE_ENERGETICA',
        'OGGETTO_ALTRO', 'OGGETTO_ALTRO_TXT', 'REGIONE'],
       dtype='object'))

In [11]:
# ============================================
# 10.7.5 – Search for cooling-related variables
# ============================================

cool_keywords = ["RAFFRESC", "ESTIV", "ESTIVA", "ESTIVO", "RAFFR", "COOL"]
cool_cols = [c for c in epc_sample.columns if any(k in c.upper() for k in cool_keywords)]

print("Cooling-related columns found:")
for c in cool_cols:
    print("  -", c)

Cooling-related columns found:
  - SUPERF_UTILE_RAFFRESCATA
  - VOLUME_LORDO_RAFFRESCATO
  - CLIMATIZZAZIONE_ESTIVA
  - CONSUMI_TELERAFFRESCAMENTO

In [12]:
# ============================================
# 10.7.6 – Inspect possible coordinate / join fields
# ============================================

cols_to_check = ["COMUNE", "INDIRIZZO", "PI", "PE", "Y", "Z"]

for col in cols_to_check:
    if col in epc_sample.columns:
        print(f"\nColumn: {col}")
        print(epc_sample[col].head())

Column: COMUNE
0    MILANO
1    MILANO
2    MILANO
3    MILANO
4    MILANO
Name: COMUNE, dtype: object

Column: INDIRIZZO
0       fontanelli 10
1     Via Caldirola 6
2     Via G. Silva 43
3       VIA MAHON 119
4    Viale Tunisia 42
Name: INDIRIZZO, dtype: object

Column: PI
0    red
1    red
2    red
3    red
4    red
Name: PI, dtype: object

Column: PE
0       red
1       red
2    yellow
3       red
4    yellow
Name: PE, dtype: object

Column: Y
0     C (64,47)
1      B (99,4)
2     B (42,87)
3     B (82,17)
4    A1 (72,45)
Name: Y, dtype: object

Column: Z
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Z, dtype: float64

In [13]:
# (For later) – will be used once we load the full dataset

# epc_full = pd.read_csv(epc_path, sep=",", low_memory=False)
# epc_milan = epc_full[epc_full["COMUNE_CATASTALE"] == "MILANO"].copy()
# epc_milan.shape

In [14]:
# ============================================
# STAGE 10.7.8 — EPC CLEANING & STANDARDIZATION
# Step 1: Load full EPC (CENED+2) dataset
# ============================================

import pandas as pd
from pathlib import Path

# Folder where CENED files are stored
base_cened = Path(r"F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED")

# Main EPC dataset (cleaned CENED+2 CSV)
epc_path = base_cened / "Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv"

print("EPC path:", epc_path)
print("Exists:", epc_path.exists())

# Load full EPC dataset
epc = pd.read_csv(epc_path, sep=",", low_memory=False)

print("Raw EPC shape:", epc.shape)
epc.head()

EPC path: F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\Database_CENED+2_-_Certificazione_ENergetica_degli_EDifici_20251128.csv
Exists: True
Raw EPC shape: (342684, 198)

,COD_APE,DATA_INS,RESIDENZIALE,NON_RESIDENZIALE,COMUNE_CATASTALE,PROPRIETA_PUBBLICA,USO_PUBBLICO,CLASSIFICAZIONE_DPR,INTERO_EDIFICIO,UNITA_IMMOBILIARE,...,TPC_EPNREN_2,SOPRALLUOGO,SW_REQUISITI,SW_SEMPLIFICATO,ENTE_PUBBLICO,TECNICO_ABILITATO,SOCIETA,TITOLO_CERT,ORDINE_CERT,SEZ_CENSIMENTO
0,1514602104118,13/09/2018,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in ingegneria,Ordine degli ingegneri,NaN
1,1514600314321,28/01/2021,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in architettura,Ordine degli architetti,NaN
2,1514602122717,24/07/2017,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di geometra,Collegio dei geometri,NaN
3,1514601459317,24/05/2017,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di perito industriale o di istruzione ...,Collegio dei periti industriali,NaN
4,1514603613816,19/12/2016,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in architettura,Ordine degli architetti,NaN

In [15]:
# ============================================
# 10.7.8.2 — Load EPC dataset & inspect
# ============================================

epc = pd.read_csv(epc_path, sep=",", low_memory=False)

print("Raw EPC shape:", epc.shape)

epc.head()

Raw EPC shape: (342684, 198)

,COD_APE,DATA_INS,RESIDENZIALE,NON_RESIDENZIALE,COMUNE_CATASTALE,PROPRIETA_PUBBLICA,USO_PUBBLICO,CLASSIFICAZIONE_DPR,INTERO_EDIFICIO,UNITA_IMMOBILIARE,...,TPC_EPNREN_2,SOPRALLUOGO,SW_REQUISITI,SW_SEMPLIFICATO,ENTE_PUBBLICO,TECNICO_ABILITATO,SOCIETA,TITOLO_CERT,ORDINE_CERT,SEZ_CENSIMENTO
0,1514602104118,13/09/2018,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in ingegneria,Ordine degli ingegneri,NaN
1,1514600314321,28/01/2021,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in architettura,Ordine degli architetti,NaN
2,1514602122717,24/07/2017,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di geometra,Collegio dei geometri,NaN
3,1514601459317,24/05/2017,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di perito industriale o di istruzione ...,Collegio dei periti industriali,NaN
4,1514603613816,19/12/2016,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in architettura,Ordine degli architetti,NaN

In [16]:
# ============================================
# 10.7.8.3 — Filter EPC dataset to MILAN only
# ============================================

epc_milan = epc[epc["COMUNE_CATASTALE"] == "MILANO"].copy()

print("Milan EPC shape:", epc_milan.shape)

epc_milan.head()

Milan EPC shape: (342684, 198)

,COD_APE,DATA_INS,RESIDENZIALE,NON_RESIDENZIALE,COMUNE_CATASTALE,PROPRIETA_PUBBLICA,USO_PUBBLICO,CLASSIFICAZIONE_DPR,INTERO_EDIFICIO,UNITA_IMMOBILIARE,...,TPC_EPNREN_2,SOPRALLUOGO,SW_REQUISITI,SW_SEMPLIFICATO,ENTE_PUBBLICO,TECNICO_ABILITATO,SOCIETA,TITOLO_CERT,ORDINE_CERT,SEZ_CENSIMENTO
0,1514602104118,13/09/2018,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in ingegneria,Ordine degli ingegneri,NaN
1,1514600314321,28/01/2021,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in architettura,Ordine degli architetti,NaN
2,1514602122717,24/07/2017,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di geometra,Collegio dei geometri,NaN
3,1514601459317,24/05/2017,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di perito industriale o di istruzione ...,Collegio dei periti industriali,NaN
4,1514603613816,19/12/2016,True,False,MILANO,False,False,E.1(1),False,True,...,0.0,True,True,False,False,True,False,Diploma di laurea in architettura,Ordine degli architetti,NaN

In [17]:
# ============================================
# 10.7.8.4 — Select core ML + merging columns
# ============================================

core_cols = [
    # Identification / address
    "COD_APE",
    "DATA_INS",
    "COMUNE",
    "INDIRIZZO",

    # Building characteristics
    "ANNO_COSTRUZIONE",

    # ML target variables
    "EP_GL_NREN",
    "EP_GL_REN",
    "CLASSE_ENERGETICA",

    # Cooling-related predictors
    "CLIMATIZZAZIONE_ESTIVA",
    "SUPERF_UTILE_RAFFRESCATA",
    "VOLUME_LORDO_RAFFRESCATO",
    "CONSUMI_TELERAFFRESCAMENTO",
]

epc_clean = epc_milan[core_cols].copy()

print("Clean EPC shape:", epc_clean.shape)
epc_clean.head()

Clean EPC shape: (342684, 12)

,COD_APE,DATA_INS,COMUNE,INDIRIZZO,ANNO_COSTRUZIONE,EP_GL_NREN,EP_GL_REN,CLASSE_ENERGETICA,CLIMATIZZAZIONE_ESTIVA,SUPERF_UTILE_RAFFRESCATA,VOLUME_LORDO_RAFFRESCATO,CONSUMI_TELERAFFRESCAMENTO
0,1514602104118,13/09/2018,MILANO,fontanelli 10,1960,115.02,9.52,E,False,0.00,0.00,0.0
1,1514600314321,28/01/2021,MILANO,Via Caldirola 6,1993-2006,228.46,3.98,F,True,73.14,254.46,0.0
2,1514602122717,24/07/2017,MILANO,Via G. Silva 43,1946-1960,81.39,0.07,D,False,0.00,0.00,0.0
3,1514601459317,24/05/2017,MILANO,VIA MAHON 119,1955,262.98,3.94,F,True,46.10,165.00,0.0
4,1514603613816,19/12/2016,MILANO,Viale Tunisia 42,1930,187.94,9.43,E,True,106.40,450.00,0.0

In [18]:
# ============================================
# 10.7.8.5 — Basic Cleaning (dates + numeric + missing values)
# ============================================

# 1. Convert DATA_INS to datetime (day-first format)
epc_clean["DATA_INS"] = pd.to_datetime(epc_clean["DATA_INS"], errors="coerce", dayfirst=True)

# 2. Convert numeric columns
numeric_cols = [
    "EP_GL_NREN",
    "EP_GL_REN",
    "SUPERF_UTILE_RAFFRESCATA",
    "VOLUME_LORDO_RAFFRESCATO",
    "CONSUMI_TELERAFFRESCAMENTO",
]

for col in numeric_cols:
    epc_clean[col] = pd.to_numeric(epc_clean[col], errors="coerce")

# 3. Show missing values summary
missing_summary = epc_clean.isna().sum()

missing_summary

COD_APE                          0
DATA_INS                         0
COMUNE                           0
INDIRIZZO                        0
ANNO_COSTRUZIONE                 0
EP_GL_NREN                       0
EP_GL_REN                        0
CLASSE_ENERGETICA                0
CLIMATIZZAZIONE_ESTIVA           0
SUPERF_UTILE_RAFFRESCATA         0
VOLUME_LORDO_RAFFRESCATO         0
CONSUMI_TELERAFFRESCAMENTO    2673
dtype: int64

In [19]:
# ============================================
# 10.7.8.5 — Basic Cleaning (dates + numeric + missing values)
# ============================================

# 1. Convert DATA_INS to datetime (day-first format)
epc_clean["DATA_INS"] = pd.to_datetime(epc_clean["DATA_INS"], errors="coerce", dayfirst=True)

# 2. Convert numeric columns
numeric_cols = [
    "EP_GL_NREN",
    "EP_GL_REN",
    "SUPERF_UTILE_RAFFRESCATA",
    "VOLUME_LORDO_RAFFRESCATO",
    "CONSUMI_TELERAFFRESCAMENTO",
]

for col in numeric_cols:
    epc_clean[col] = pd.to_numeric(epc_clean[col], errors="coerce")

# 3. Show missing values summary
missing_summary = epc_clean.isna().sum()

missing_summary

COD_APE                          0
DATA_INS                         0
COMUNE                           0
INDIRIZZO                        0
ANNO_COSTRUZIONE                 0
EP_GL_NREN                       0
EP_GL_REN                        0
CLASSE_ENERGETICA                0
CLIMATIZZAZIONE_ESTIVA           0
SUPERF_UTILE_RAFFRESCATA         0
VOLUME_LORDO_RAFFRESCATO         0
CONSUMI_TELERAFFRESCAMENTO    2673
dtype: int64

In [20]:
# ============================================
# 10.7.8.6 — Normalize address field
# ============================================

# Work on a copy of the address string
addr = epc_clean["INDIRIZZO"].astype(str)

# 1) Uppercase
addr = addr.str.upper()

# 2) Strip leading/trailing spaces
addr = addr.str.strip()

# 3) Collapse multiple spaces into one
addr = addr.str.replace(r"\s+", " ", regex=True)

# Save as new column
epc_clean["INDIRIZZO_NORM"] = addr

print("Example normalized addresses:")
print(epc_clean[["INDIRIZZO", "INDIRIZZO_NORM"]].head())

Example normalized addresses:
          INDIRIZZO    INDIRIZZO_NORM
0     fontanelli 10     FONTANELLI 10
1   Via Caldirola 6   VIA CALDIROLA 6
2   Via G. Silva 43   VIA G. SILVA 43
3     VIA MAHON 119     VIA MAHON 119
4  Viale Tunisia 42  VIALE TUNISIA 42

In [21]:
# ============================================
# 10.7.9.1 — Handle missing values
# ============================================

# Only 2673 missing values exist and they are all in CONSUMI_TELERAFFRESCAMENTO
epc_clean["CONSUMI_TELERAFFRESCAMENTO"] = epc_clean["CONSUMI_TELERAFFRESCAMENTO"].fillna(0)

# Verify again
epc_clean.isna().sum()

COD_APE                       0
DATA_INS                      0
COMUNE                        0
INDIRIZZO                     0
ANNO_COSTRUZIONE              0
EP_GL_NREN                    0
EP_GL_REN                     0
CLASSE_ENERGETICA             0
CLIMATIZZAZIONE_ESTIVA        0
SUPERF_UTILE_RAFFRESCATA      0
VOLUME_LORDO_RAFFRESCATO      0
CONSUMI_TELERAFFRESCAMENTO    0
INDIRIZZO_NORM                0
dtype: int64

In [22]:
# ============================================
# 10.7.9.2 — Clean ANNO_COSTRUZIONE
# Convert ranges like "1993-2006" to 1993
# ============================================

def clean_year(x):
    if pd.isna(x):
        return None
    x = str(x)
    # If a range, take the first part
    if "-" in x:
        return int(x.split("-")[0])
    # Otherwise convert directly
    try:
        return int(x)
    except:
        return None

epc_clean["ANNO_COSTRUZIONE_CLEAN"] = epc_clean["ANNO_COSTRUZIONE"].apply(clean_year)

# Preview
epc_clean[["ANNO_COSTRUZIONE", "ANNO_COSTRUZIONE_CLEAN"]].head(10)

  ANNO_COSTRUZIONE  ANNO_COSTRUZIONE_CLEAN
0             1960                  1960.0
1        1993-2006                  1993.0
2        1946-1960                  1946.0
3             1955                  1955.0
4             1930                  1930.0
5     Dopo il 2006                     NaN
6     Dopo il 2006                     NaN
7             1952                  1952.0
8        1930-1945                  1930.0
9        1961-1976                  1961.0

In [23]:
# ============================================
# 10.7.9.3 — Final EPC cleaning
# ============================================

# 1. Fill missing construction years with the median of valid years
median_year = epc_clean["ANNO_COSTRUZIONE_CLEAN"].median()
epc_clean["ANNO_COSTRUZIONE_CLEAN"] = epc_clean["ANNO_COSTRUZIONE_CLEAN"].fillna(median_year)

# Convert to integer
epc_clean["ANNO_COSTRUZIONE_CLEAN"] = epc_clean["ANNO_COSTRUZIONE_CLEAN"].astype(int)

# 2. Build final dataset
epc_clean_final = epc_clean[[
    "COD_APE", "DATA_INS", "COMUNE", "INDIRIZZO", "INDIRIZZO_NORM",
    "ANNO_COSTRUZIONE_CLEAN", 
    "EP_GL_NREN", "EP_GL_REN", "CLASSE_ENERGETICA",
    "CLIMATIZZAZIONE_ESTIVA",
    "SUPERF_UTILE_RAFFRESCATA", "VOLUME_LORDO_RAFFRESCATO",
    "CONSUMI_TELERAFFRESCAMENTO"
]]

print("Final EPC dataset shape:", epc_clean_final.shape)
epc_clean_final.head()

Final EPC dataset shape: (342684, 13)

,COD_APE,DATA_INS,COMUNE,INDIRIZZO,INDIRIZZO_NORM,ANNO_COSTRUZIONE_CLEAN,EP_GL_NREN,EP_GL_REN,CLASSE_ENERGETICA,CLIMATIZZAZIONE_ESTIVA,SUPERF_UTILE_RAFFRESCATA,VOLUME_LORDO_RAFFRESCATO,CONSUMI_TELERAFFRESCAMENTO
0,1514602104118,2018-09-13,MILANO,fontanelli 10,FONTANELLI 10,1960,115.02,9.52,E,False,0.00,0.00,0.0
1,1514600314321,2021-01-28,MILANO,Via Caldirola 6,VIA CALDIROLA 6,1993,228.46,3.98,F,True,73.14,254.46,0.0
2,1514602122717,2017-07-24,MILANO,Via G. Silva 43,VIA G. SILVA 43,1946,81.39,0.07,D,False,0.00,0.00,0.0
3,1514601459317,2017-05-24,MILANO,VIA MAHON 119,VIA MAHON 119,1955,262.98,3.94,F,True,46.10,165.00,0.0
4,1514603613816,2016-12-19,MILANO,Viale Tunisia 42,VIALE TUNISIA 42,1930,187.94,9.43,E,True,106.40,450.00,0.0

In [24]:
# ============================================
# 10.7.9.4 — Save EPC clean dataset
# ============================================

save_path = r"F:\Building Engineering - Polytechnic University of Turin\Masters Thesis\23-11-2025\Data Collections\CENED\epc_clean_final.csv"
epc_clean_final.to_csv(save_path, index=False)

save_path

'F:\\Building Engineering - Polytechnic University of Turin\\Masters Thesis\\23-11-2025\\Data Collections\\CENED\\epc_clean_final.csv'